### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by FerDR89** [PabloMur/desafio7#2]
Buenas Pablo, ¿Cómo va? Que bueno que hayas llegado hasta acá!

Te dejo algunas cosas que vi del desafío;

Cuando comparto mi ubicación me lleva a MDP (vivo aprox 450+ km), no te esta tomando las coordenadas que le paso y por eso no encuentra las mascotas cercanas que reporte.

![image](https://user-images.githubusercontent.com/74626765/200827838-4df8f673-c0cf-4d67-bb62-d3e5e2dc071b.png)

Le agregaría la prop cursor: pointer a todos los botones como tenes en el logo de la web

![image](https://user-images.githubusercontent.com/74626765/200828056-f22381c1-9d23-40a5-a415-e9d9ab93de91.png)

En esta page debería de poder cambiar mi password

![image](https://user-images.githubusercontent.com/74626765/200828367-8fee0a19-a738-42ef-a4e9-4a027ba519b3.png)

No me deja editar la mascota
![image](https://user-images.githubusercontent.com/74626765/200829313-706e79f5-93a8-402b-9630-9560e4e003c6.png)

Si ya estoy logeado los botones de login sign up no debería estar, si debería de estar el email del user

**Comment by PabloMur** [comment]
Joya Fer! Ahora lo reviso y aviso cuando lo tenga resuelto
